// Generates a colour-only theme overlay from an existing stylesheet.
//
//   dart run tool/gen_theme_overlay.dart <input.css> <output.css> dark
//   dart run tool/gen_theme_overlay.dart <input.css> <output.css> light
//
// `dark` derives a dark overlay from a light-native stylesheet (Studio),
// `light` derives a light overlay from a dark-native one (Admin). Every rule
// that sets a colour is re-emitted under `:root[data-theme="<mode>"]` with only
// the colour declarations remapped, so the source stylesheet is never edited.
// Re-run after changing the source stylesheet.
import 'dart:io';
import 'dart:math' as math;

void main(List<String> args) {
  if (args.length != 3 || (args[2] != 'dark' && args[2] != 'light')) {
    stderr.writeln(
      'usage: dart run tool/gen_theme_overlay.dart <in.css> <out.css> dark|light',
    );
    exit(64);
  }
  final mode = args[2];
  final source = File(args[0]).readAsStringSync().replaceAll('\r\n', '\n');
  final gen = _Generator(mode);
  final body = gen.processBlock(_stripComments(source));
  final scheme = mode == 'dark' ? 'dark' : 'light';
  File(args[1]).writeAsStringSync(
    '/* GENERATED by tool/gen_theme_overlay.dart from ${args[0].split(RegExp(r'[\\/]')).last} ($mode overlay). Do not edit. */\n'
    ':root[data-theme="$mode"] {\n  color-scheme: $scheme;\n}\n\n'
    '$body',
  );
  stdout.writeln('wrote ${args[1]} (${gen.rules} rules)');
}

String _stripComments(String css) =>
    css.replaceAll(RegExp(r'/\*[\s\S]*?\*/'), '');

enum _Kind { bg, text, border }

const _bgProps = {'background', 'background-color', 'background-image'};
const _borderProps = {
  'border',
  'border-color',
  'border-top',
  'border-right',
  'border-bottom',
  'border-left',
  'border-top-color',
  'border-right-color',
  'border-bottom-color',
  'border-left-color',
  'border-block',
  'border-inline',
  'outline',
  'outline-color',
  'column-rule',
};
const _textProps = {
  'color',
  'fill',
  'stroke',
  'caret-color',
  'text-decoration-color',
  '-webkit-text-fill-color',
};

class _Generator {
  _Generator(this.mode) : prefix = ':root[data-theme="$mode"]';

  final String mode;
  final String prefix;
  int rules = 0;

  /// Processes a sequence of rules / at-rules and returns the overlay CSS.
  String processBlock(String css) {
    final out = StringBuffer();
    var i = 0;
    while (i < css.length) {
      while (i < css.length && css[i].trim().isEmpty) {
        i++;
      }
      if (i >= css.length) break;

      final open = _find(css, '{', i);
      final semi = _find(css, ';', i);
      if (open == -1) break;
      if (semi != -1 && semi < open && css[i] == '@') {
        i = semi + 1; // @import / @charset
        continue;
      }
      final prelude = css.substring(i, open).trim();
      final close = _matchBrace(css, open);
      final inner = css.substring(open + 1, close);
      i = close + 1;

      if (prelude.startsWith('@')) {
        final name = prelude.split(RegExp(r'[\s(]')).first;
        if (name == '@media' || name == '@supports' || name == '@layer') {
          final nested = processBlock(inner);
          if (nested.trim().isNotEmpty) {
            out.write('$prelude {\n$nested}\n\n');
          }
        }
        continue; // @keyframes, @font-face, … carry no theme colours
      }

      final decls = _transformDeclarations(inner);
      if (decls.isEmpty) continue;
      final selectors = _splitTop(prelude, ',').map(_prefixSelector).join(',\n');
      out.write('$selectors {\n${decls.map((d) => '  $d;\n').join()}}\n\n');
      rules++;
    }
    return out.toString();
  }

  String _prefixSelector(String selector) {
    final s = selector.trim();
    if (s == ':root' || s == 'html') return prefix;
    if (s.startsWith(':root ')) return '$prefix ${s.substring(6)}';
    if (s.startsWith('html ')) return '$prefix ${s.substring(5)}';
    return '$prefix $s';
  }

  List<String> _transformDeclarations(String block) {
    final result = <String>[];
    for (final raw in _splitTop(block, ';')) {
      final colon = raw.indexOf(':');
      if (colon == -1) continue;
      final prop = raw.substring(0, colon).trim().toLowerCase();
      var value = raw.substring(colon + 1).trim();
      final _Kind kind;
      if (_bgProps.contains(prop)) {
        kind = _Kind.bg;
      } else if (_borderProps.contains(prop)) {
        kind = _Kind.border;
      } else if (_textProps.contains(prop)) {
        kind = _Kind.text;
      } else {
        continue;
      }
      var important = '';
      final imp = RegExp(r'\s*!important\s*$').firstMatch(value);
      if (imp != null) {
        important = ' !important';
        value = value.substring(0, imp.start);
      }
      final mapped = _mapColors(value, kind);
      if (mapped == value) continue;
      result.add('$prop: $mapped$important');
    }
    return result;
  }

  static final _colorRe = RegExp(
    r'#[0-9a-fA-F]{8}\b|#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{3,4}\b|rgba?\([^)]*\)|(?<![\w-])(?:white|black)(?![\w-])',
    caseSensitive: false,
  );

  String _mapColors(String value, _Kind kind) {
    // Leave url(...) payloads alone.
    final parts = <String>[];
    var last = 0;
    for (final m in RegExp(r'url\([^)]*\)').allMatches(value)) {
      parts.add(_mapSegment(value.substring(last, m.start), kind));
      parts.add(m.group(0)!);
      last = m.end;
    }
    parts.add(_mapSegment(value.substring(last), kind));
    return parts.join();
  }

  String _mapSegment(String segment, _Kind kind) {
    return segment.replaceAllMapped(_colorRe, (m) {
      final c = _parse(m.group(0)!);
      if (c == null) return m.group(0)!;
      final mapped = mode == 'dark' ? _toDark(c, kind) : _toLight(c, kind);
      return _format(mapped);
    });
  }

  // ---------------------------------------------------------------- mapping

  /// Greys and blue-greys (slate/navy text, page backgrounds): treated as
  /// neutrals so they flip with lightness instead of keeping a saturated hue.
  bool _neutral(_Color c) =>
      c.s < 0.15 || (c.h >= 195 && c.h <= 260 && c.s < 0.6);

  _Color _toDark(_Color c, _Kind kind) {
    final s = c.s, l = c.l;
    final neutral = _neutral(c);
    switch (kind) {
      case _Kind.bg:
        if (s < 0.2 && l >= 0.995) return c.with_(h: 221, s: 0.39, l: 0.115);
        if (neutral) {
          if (l >= 0.93) {
            final t = (l - 0.93) / 0.07;
            return c.with_(h: 222, s: 0.35, l: 0.05 + t * 0.035);
          }
          if (l >= 0.80) {
            final t = (0.93 - l) / 0.13;
            return c.with_(h: 220, s: 0.3, l: 0.15 + t * 0.10);
          }
          if (l >= 0.5) {
            return c.with_(h: 218, s: 0.25, l: 0.25 + (0.80 - l) / 0.30 * 0.12);
          }
          return c;
        }
        if (l >= 0.85) {
          return c.with_(
            s: math.min(s, 0.5) * 0.6,
            l: (0.10 + (1 - l) * 0.55).clamp(0.10, 0.20),
          );
        }
        if (l > 0.7) return c.with_(l: l - 0.3);
        return c;
      case _Kind.text:
        if (l >= 0.93) return c;
        if (neutral) {
          if (l >= 0.7) return c;
          return c.with_(h: 215, s: 0.2, l: (0.93 - 0.55 * l).clamp(0.55, 0.9));
        }
        if (l < 0.7) {
          return c.with_(s: math.min(s, 0.8), l: (l + 0.25).clamp(0.62, 0.78));
        }
        return c;
      case _Kind.border:
        if (l >= 0.8) {
          if (neutral) {
            return c.with_(
              h: 218,
              s: 0.25,
              l: (0.19 + (0.91 - l) * 0.9).clamp(0.12, 0.30),
            );
          }
          return c.with_(s: s * 0.5, l: 0.22);
        }
        if (l >= 0.5 && neutral) {
          return c.with_(h: 218, s: 0.2, l: (0.30 + (0.8 - l) * 0.3).clamp(0.3, 0.4));
        }
        return c;
    }
  }

  _Color _toLight(_Color c, _Kind kind) {
    final s = c.s, l = c.l;
    switch (kind) {
      case _Kind.bg:
        if (s < 0.35 && l < 0.5) {
          if (l < 0.075) return c.with_(h: 210, s: 0.29, l: 0.965);
          if (l < 0.115) return c.with_(h: 0, s: 0, l: 1);
          return c.with_(h: 210, s: 0.25, l: (0.95 - (l - 0.115) * 0.9).clamp(0.6, 0.95));
        }
        if (l < 0.22 && s >= 0.35) {
          return c.with_(s: math.min(s, 0.6) * 0.8, l: (0.90 + l * 0.1).clamp(0.9, 0.95));
        }
        return c;
      case _Kind.text:
        if (l >= 0.97) return c;
        if (s < 0.4 && l >= 0.5) {
          return c.with_(h: 215, s: 0.18, l: (0.95 * (1 - l) + 0.04).clamp(0.08, 0.45));
        }
        if (l >= 0.5) {
          return c.with_(s: math.min(s, 0.85), l: (l - 0.22).clamp(0.32, 0.45));
        }
        return c;
      case _Kind.border:
        if (l < 0.5 && s < 0.4) {
          return c.with_(h: 210, s: 0.18, l: (1.03 - l).clamp(0.78, 0.92));
        }
        if (l < 0.22 && s >= 0.4) return c.with_(l: 0.75);
        return c;
    }
  }

  // ---------------------------------------------------------------- parsing

  _Color? _parse(String text) {
    final t = text.toLowerCase();
    if (t == 'white') return _Color.rgb(255, 255, 255, 1);
    if (t == 'black') return _Color.rgb(0, 0, 0, 1);
    if (t.startsWith('#')) {
      var hex = t.substring(1);
      if (hex.length == 3 || hex.length == 4) {
        hex = hex.split('').map((ch) => '$ch$ch').join();
      }
      final r = int.parse(hex.substring(0, 2), radix: 16);
      final g = int.parse(hex.substring(2, 4), radix: 16);
      final b = int.parse(hex.substring(4, 6), radix: 16);
      final a = hex.length == 8 ? int.parse(hex.substring(6, 8), radix: 16) / 255 : 1.0;
      return _Color.rgb(r, g, b, a);
    }
    final nums = RegExp(r'[\d.]+%?')
        .allMatches(t.substring(t.indexOf('(')))
        .map((m) => m.group(0)!)
        .toList();
    if (nums.length < 3) return null;
    double ch(String v) => v.endsWith('%')
        ? double.parse(v.substring(0, v.length - 1)) * 2.55
        : double.parse(v);
    final a = nums.length > 3
        ? (nums[3].endsWith('%')
              ? double.parse(nums[3].substring(0, nums[3].length - 1)) / 100
              : double.parse(nums[3]))
        : 1.0;
    return _Color.rgb(ch(nums[0]).round(), ch(nums[1]).round(), ch(nums[2]).round(), a);
  }

  String _format(_Color c) {
    final (r, g, b) = c.toRgb();
    if (c.a >= 0.999) {
      String x(int v) => v.toRadixString(16).padLeft(2, '0');
      return '#${x(r)}${x(g)}${x(b)}';
    }
    final alpha = double.parse(c.a.toStringAsFixed(3));
    return 'rgba($r, $g, $b, $alpha)';
  }

  // ---------------------------------------------------------------- scanning

  int _find(String s, String ch, int from) {
    var depth = 0;
    String? quote;
    for (var i = from; i < s.length; i++) {
      final c = s[i];
      if (quote != null) {
        if (c == quote && s[i - 1] != '\\') quote = null;
        continue;
      }
      if (c == '"' || c == "'") {
        quote = c;
      } else if (c == '(') {
        depth++;
      } else if (c == ')') {
        depth--;
      } else if (c == ch && depth == 0) {
        return i;
      }
    }
    return -1;
  }

  int _matchBrace(String s, int open) {
    var depth = 0;
    String? quote;
    for (var i = open; i < s.length; i++) {
      final c = s[i];
      if (quote != null) {
        if (c == quote && s[i - 1] != '\\') quote = null;
        continue;
      }
      if (c == '"' || c == "'") {
        quote = c;
      } else if (c == '{') {
        depth++;
      } else if (c == '}') {
        depth--;
        if (depth == 0) return i;
      }
    }
    return s.length - 1;
  }

  List<String> _splitTop(String s, String sep) {
    final parts = <String>[];
    var depth = 0;
    var start = 0;
    String? quote;
    for (var i = 0; i < s.length; i++) {
      final c = s[i];
      if (quote != null) {
        if (c == quote && s[i - 1] != '\\') quote = null;
        continue;
      }
      if (c == '"' || c == "'") {
        quote = c;
      } else if (c == '(' || c == '[') {
        depth++;
      } else if (c == ')' || c == ']') {
        depth--;
      } else if (c == sep && depth == 0) {
        parts.add(s.substring(start, i));
        start = i + 1;
      }
    }
    parts.add(s.substring(start));
    return parts.where((p) => p.trim().isNotEmpty).toList();
  }
}

class _Color {
  _Color(this.h, this.s, this.l, this.a);

  factory _Color.rgb(int r, int g, int b, double a) {
    final rf = r / 255, gf = g / 255, bf = b / 255;
    final maxC = math.max(rf, math.max(gf, bf));
    final minC = math.min(rf, math.min(gf, bf));
    final l = (maxC + minC) / 2;
    var h = 0.0, s = 0.0;
    final d = maxC - minC;
    if (d != 0) {
      s = l > 0.5 ? d / (2 - maxC - minC) : d / (maxC + minC);
      if (maxC == rf) {
        h = ((gf - bf) / d + (gf < bf ? 6 : 0)) * 60;
      } else if (maxC == gf) {
        h = ((bf - rf) / d + 2) * 60;
      } else {
        h = ((rf - gf) / d + 4) * 60;
      }
    }
    return _Color(h, s, l, a);
  }

  final double h, s, l, a;

  _Color with_({double? h, double? s, double? l}) =>
      _Color(h ?? this.h, s ?? this.s, l ?? this.l, a);

  (int, int, int) toRgb() {
    double f(double n) {
      final k = (n + h / 30) % 12;
      final aa = s * math.min(l, 1 - l);
      return l - aa * math.max(-1, math.min(math.min(k - 3, 9 - k), 1));
    }

    int c(double v) => (v * 255).round().clamp(0, 255);
    return (c(f(0)), c(f(8)), c(f(4)));
  }
}
